### ISSUE TITLE
[RFE] Set custom metric-profiles from flag

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner-ocp#110]
**Is your feature request related to a problem? Please describe.**

With the current implementation, each workload has predefined a metric-profile (metrics.yml, metrics-aggregated.yml, metrics-egress.yml, etc), it would be useful to allow the user to use an external metric-profile

**Describe the solution you'd like**

A metric-profile list can be passed as a flagThat metric profile can be passed from a flag, i.e:

```shell
 ./bin/amd64/kube-burner-ocp cluster-density-v2 --iterations=10 --metrics-profile=custom-metrics.yml,more-metrics.yml
```

If this flag is not set, kube-burner will follow the previous behavior, of using the pre-defined embedded metrics-profile of the workload in question.

**Describe alternatives you've considered**

As part of this effort, we can end up deprecating the flag `--profile-type`, that would mean that the files specified by `--metrics-profile` can also be embedded in the kube-burner-ocp binary

**Additional context**

Having this PR can help to fix issues like the one that is trying to fix with https://github.com/kube-burner/kube-burner-ocp/pull/103, which basically is extending  the default metrics profile with not relevant prometheus expresions for standards clusters due to the impossibility of using a different metrics-profile rather than the default one.

**Comment by vishnuchalla** [comment]
@rsevilla87 If we simply deprecate `--profile-type` flag, it might impact our CI jobs. JFYI.
Also there is a bug: https://github.com/kube-burner/kube-burner/issues/683 which is relevant to this. Hoping that to be fixed as well with this change.
