### ISSUE TITLE
[RFE] OpenShift cluster health checks

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner-ocp#17]
**Is your feature request related to a problem? Please describe.**

Taking advantage of the new parameter `clusterHealth` added in https://github.com/kube-burner/kube-burner/pull/585, add a series of OpenShift cluster health checks including:

- Cluster-operator status, we can reuse part of the code of the verifyContainerRegistry() function. https://github.com/kube-burner/kube-burner-ocp/blob/main/common.go#L47-L84

**Describe the solution you'd like**

Check readiness of all OpenShiftt clusteroperators

**Comment by rsevilla87** [comment]
cc: @shashank-boyapally

**Comment by shashank-boyapally** [comment]
Will be adding this to ocp as well
