### ISSUE TITLE
[RFE] OCP-CI for ppc64le for release testing 

### ISSUE THREAD

**Issue by varad-ahirwadkar** [kube-burner/kube-burner-ocp#74]
Is your feature request related to a problem? Please describe.
There is no release testing CI for kube-burner `ppc64le` binary.

Describe the solution you'd like
ppc64le CI for release testing prior publishing the binaries.

**Comment by krishvoor** [comment]
Hi @varad-ahirwadkar: thanks for your proposal, the container image as part of [CI testing](https://github.com/kube-burner/kube-burner-ocp/blob/main/test/test-ocp.bats#L32-L116) are multi-arch, you can perform a CI-test similar to
ARM images https://github.com/krishvoor/kube-burner-ocp/actions/runs/9318213301/job/25675155014
