### ISSUE TITLE
[RFE] Write output to log file

### ISSUE THREAD

**Issue by afcollins** [kube-burner/kube-burner-ocp#90]
**Is your feature request related to a problem? Please describe.**
We have this [feature](https://github.com/kube-burner/kube-burner/issues/641) in kube-burner, but we also want to use it from kube-burner-ocp.

**Describe the solution you'd like**
Capture the kube-burner output to a file.

The default filename is fine as it is uniquely generated.
Would be nice to have a toggle to be able to turn it off if desired, and maybe a way to change the file name (optional. The file name works for me).

**Describe alternatives you've considered**
When I do runs locally, I use tee -a to write to a local file. It usually looks like this:

```
kube-burner init ... 2>&1 | tee -a kube-burner.$(date +"%F-%H%M%S").log
```

**Additional context**
Same as from the linked issue in kube-burner.

**Comment by shashank-boyapally** [comment]
Will add it to kb-ocp as well

**Comment by vishnuchalla** [comment]
Closing as complete: https://github.com/kube-burner/kube-burner-ocp/pull/96
